baseURL = 'https://bist.be/'
languageCode = 'en-us'
title = 'Bist.be'
copyright = "2024 Bist.be"
timeZone = "Europe/Brussels"


[module]
  # this is needed when you fetch the theme as a submodule to your repo.
  # replacements = "github.com/panr/hugo-theme-terminal/4 -> themes/terminal"
[[module.imports]]
  path = 'github.com/panr/hugo-theme-terminal/v4'

[params]
# contentTypeName = "posts"
  showMenuItems = 5
  centerTheme = true
  autoCover = true
  cover = "/hello.jpg"
  dateFormat = "02-01-2006"
  [params.logo]
    logotext = "Bist.be"



[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Apps I use'
    pageRef = '/pages/apps'
    weight = 20
  [[menus.main]]
    name = 'About'
    pageRef = '/pages/about'
    weight = 30


